### ISSUE TITLE
 JS and Java conflict

### ISSUE THREAD

**Issue by PumpkinatorProductions** [PumpkinatorProductions/vigilant-potato#2]
- Which one, JFrame vs. canvas?
- Functionality in one language only
# Todo

---
- [ ] [Java](https://github.com/PumpkinatorProductions/vigilant-potato/blob/master/main.java) and [JS](https://github.com/PumpkinatorProductions/vigilant-potato/blob/master/main.js) **[language interoperability](https://en.wikipedia.org/wiki/Language_interoperability)**
  - [ ] **[.NET Framework](https://en.wikipedia.org/wiki/.NET_Framework)**
  - [ ] **[CLI languages](https://en.wikipedia.org/wiki/List_of_CLI_languages)** (combine after compile)
  - [ ] **[Virtual Machines](https://en.wikipedia.org/wiki/Virtual_machine)**
- [ ] **Langauge Docs**
  - [X] @PumpkinatorProductions [JavaScript Docs](https://github.com/PumpkinatorProductions/vigilant-potato/blob/master/ProcessingJS-Doc.md)
  - [ ] @sumeetk321 Java Docs.
